"""Select a feature specification from comparison results and write a spec JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from shared_utils import require_existing_path


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[2]

    parser = argparse.ArgumentParser(
        description="Select a hedonic feature specification from comparison output."
    )
    parser.add_argument(
        "--comparison-csv",
        type=Path,
        default=repo_root / "hedonic" / "artifacts" / "residential_hedonic_model_comparison.csv",
        help="Comparison table generated by hedonic/compare_models.py.",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=repo_root / "hedonic" / "artifacts" / "residential_hedonic_selected_spec.json",
        help="Output path for selected feature spec JSON.",
    )
    parser.add_argument(
        "--primary-metric",
        type=str,
        default="r2_level",
        choices=["r2_level", "r2_log"],
        help="Primary selection metric.",
    )
    parser.add_argument(
        "--secondary-metric",
        type=str,
        default="r2_log",
        choices=["r2_level", "r2_log"],
        help="Tie-break metric.",
    )

    args = parser.parse_args()
    args.comparison_csv = require_existing_path(args.comparison_csv, "Comparison CSV")
    args.output_json = args.output_json.expanduser().resolve()
    return args


def _parse_features(raw_features: str) -> list[str]:
    return [part.strip() for part in str(raw_features).split(",") if part.strip()]


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.comparison_csv)

    if "error" in df.columns:
        valid = df[df["error"].isna() | (df["error"].astype("string").str.strip() == "")].copy()
    else:
        valid = df.copy()

    if valid.empty:
        raise ValueError("No valid rows found in comparison CSV after filtering errors.")

    best = valid.sort_values(
        [args.primary_metric, args.secondary_metric],
        ascending=[False, False],
    ).iloc[0]

    features = _parse_features(best["features"])
    if not features:
        raise ValueError("Selected row did not contain parseable feature names.")

    payload = {
        "name": "residential_level_best_selected",
        "selected_from": str(args.comparison_csv).replace("\\", "/"),
        "selection_criterion": (
            f"highest {args.primary_metric}, tie-break highest {args.secondary_metric}, excluding errored rows"
        ),
        "features": features,
        "metrics_snapshot": {
            "r2_log": float(best["r2_log"]),
            "rmse_log": float(best["rmse_log"]),
            "r2_level": float(best["r2_level"]),
            "mae_level": float(best["mae_level"]),
            "rows_train": int(best["rows_train"]),
            "rows_test": int(best["rows_test"]),
        },
    }

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    print(f"Selected spec written: {args.output_json}")
    print("Features:", ", ".join(features))
    print(
        f"Metrics: {args.primary_metric}={payload['metrics_snapshot'][args.primary_metric]:.6f}, "
        f"{args.secondary_metric}={payload['metrics_snapshot'][args.secondary_metric]:.6f}"
    )


if __name__ == "__main__":
    main()
